---
title: Speak
timezone: UTC
collections:
  pictures:
    title: Pictures
    output: false
  posts:
    title: Posts
    output: true
  topics:
    title: Topics
    output: false
  uploads:
    title: Uploads
    output: true
name: Speak
description: Helping the world to find its voice 15 minutes at a time
primaryfont: Lato
secondaryfont: Raleway
tertiaryfont: Open Sans
color1: 
color2: 
color3: 
color4: 
color5: 
color6: 
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: speakfor15@gmail.com
  facebook: 
  flickr: 
  strava: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
  runengland: 
disqus: 
google_analytics: UA-89380340-1
url: http://www.speak.events
baseurl: https://dibdobrob.github.io/speak
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-twitter-plugin
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
